### ISSUE TITLE
Small UI fixes

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/Checkmate#1848]
- [x] Divider is not vertically aligned
- [x]  The search component is a bit "higher" than our usual 34px text input widget.

![Image](https://github.com/user-attachments/assets/22e0b717-dcc9-4e89-b032-d7612eb2000b)

- [ ] Bg color of this area to #1c1c1c and border to #515151 or nearest color

![Image](https://github.com/user-attachments/assets/b0fa2d21-3f1c-4ad4-bea7-4ff4a0345686)

- [ ] For Teams and Profile we don't really need that bounding box as it's not present in other pages.

<img width="1133" alt="Image" src="https://github.com/user-attachments/assets/84295f1d-94ef-466f-ae93-4424d89f6144" />

- [ ] Maintenance window time selector up/down boxes need a darker color from the palette

<img width="961" alt="Image" src="https://github.com/user-attachments/assets/a617e508-65fc-47db-b58b-cd6b371ef9e3" />

- [ ] The maintenance window time selector popup needs color fixes

<img width="508" alt="Image" src="https://github.com/user-attachments/assets/d80f4c12-123e-4054-bd2a-ddd76fd522c7" />

- [ ] We don't really use line edit explanation areas here, so better remove.

<img width="313" alt="Image" src="https://github.com/user-attachments/assets/504e279b-9cab-48e8-a4f8-1f67b4bf97fa" />

- [ ] Highlight colors should be fixed (should be #324153 just like the other dropdown highlight colors). This should be fixed component-wise, not just in this screen

<img width="613" alt="Image" src="https://github.com/user-attachments/assets/b96b9721-c04f-4e05-a576-8fa05df73f39" />

- [ ] Maintenance duration window notification shouldn't wrap

<img width="616" alt="Image" src="https://github.com/user-attachments/assets/7c167419-35bf-4ed2-83a3-dda21540e73c" />

- [ ] A pagination should be there only if there is a need for it.

<img width="1436" alt="Image" src="https://github.com/user-attachments/assets/55dc6896-cd17-46ef-8e9b-679852df6715" />

- [ ] While creating an infrastructure monitor, the links are invisible both for dark and light themes.

<img width="447" alt="Image" src="https://github.com/user-attachments/assets/f3c81eb3-ad7b-4572-a25b-0a0e771001d1" />

**Comment by Owaiseimdad** [comment]
Assign this to me @gorkem-bwl

**Comment by Owaiseimdad** [comment]
@gorkem-bwl , do you want to change for all the alerts or this particular?

<img width="512" alt="Image" src="https://github.com/user-attachments/assets/3d29c424-6fc2-4505-bec7-c14f1a86903c" />

**Comment by ajhollid** [comment]
@Owaiseimdad just a heads up here the color system in the theme requires a very specific format in order to work properly.

Please see existing components and color usage to see how this is done. It is not as simple as defining a color that you want for a specific fix.

**Comment by Owaiseimdad** [comment]
Yes, @ajhollid. Understood that the moment I saw some more objects in the theme file. Looks like we have can have a new key value only for alerts this will make code/theme more separated from other components.

**Comment by Owaiseimdad** [comment]
Just for my reference here, number of issues which needs to resolved in this ticket.

1. Divider is not vertically aligned
2. The search component is a bit "higher" than our usual 34px text input widget.
3. Bg colour of this area to #1c1c1c and border to #515151 or nearest colour
4. For Teams and Profile we don't really need that bounding box as it's not present in other pages.
5. Maintenance window time selector up/down boxes need a darker colour from the palette
6. The maintenance window time selector popup needs colour fixes
7. We don't really use line edit explanation areas here, so better remove.
8. Highlight colours should be fixed (should be #324153 just like the other dropdown highlight colours). This should be fixed component-wise, not just in this screen
9. Maintenance duration window notification shouldn't wrap
10. A pagination should be there only if there is a need for it.

**Comment by gorkem-bwl** [comment]
> Just for my reference here, number of issues which needs to resolved in this ticket.
> 
> 1. Divider is not vertically aligned
> 2. The search component is a bit "higher" than our usual 34px text input widget.
> 3. Bg colour of this area to #1c1c1c and border to #515151 or nearest colour
> 4. For Teams and Profile we don't really need that bounding box as it's not present in other pages.
> 5. Maintenance window time selector up/down boxes need a darker colour from the palette
> 6. The maintenance window time selector popup needs colour fixes
> 7. We don't really use line edit explanation areas here, so better remove.
> 8. Highlight colours should be fixed (should be #324153 just like the other dropdown highlight colours). This should be fixed component-wise, not just in this screen
> 9. Maintenance duration window notification shouldn't wrap
> 10. A pagination should be there only if there is a need for it.

Also, please try to send atomic PRs, maybe 1 PR for 1-3 issues, so the reviewer can focus on it without distraction :)

**Comment by ajhollid** [comment]
@Owaiseimdad some issues still remain here, I checked the ones I think are resovled, if you'd like to keep working on them we'd be happy to reivew more PRs.

Thank you for your contribution!

**Comment by Owaiseimdad** [comment]
I have raised the PR only for three @ajhollid , will raise another PR for other issues soon.

**Comment by Owaiseimdad** [comment]
@gorkem-bwl pending issues, 
1. Highlight colors should be fixed (should be #324153 just like the other dropdown highlight colors). This should be fixed component-wise, not just in this screen
2. Maintenance duration window notification shouldn't wrap
3. A pagination should be there only if there is a need for it.
4. While creating an infrastructure monitor, the links are invisible both for dark and light themes.

Will start working on them one by one and PRs will also be different for each.

**Comment by gorkem-bwl** [comment]
Sounds good!

**Comment by Owaiseimdad** [comment]
Pending issues:
1. A pagination should be there only if there is a need for it.

cc: @gorkem-bwl

**Comment by Owaiseimdad** [comment]
@gorkem-bwl You can still add more ui changes if needed 😅.

**Comment by gorkem-bwl** [comment]
Lol I doubt we are done with this. There are many sneaking around and secretly hiding from me :-D

**Comment by Owaiseimdad** [comment]
@gorkem-bwl lets close this ticket after the new PR is merged. 🙃

**Comment by Owaiseimdad** [comment]
@gorkem-bwl we are good to close this now.
