### ISSUE TITLE
Google PageSpeed API integration fails despite valid API key

### ISSUE THREAD

**Issue by draatman** [bluewave-labs/Checkmate#2198]
The PageSpeed API key works when tested manually, but when used by the application, it fails to fetch and process the lighthouseResult from the API response.

To Reproduce

Set the PAGESPEED_API_KEY in the environment variables of the Docker container.

Add a PageSpeed monitor to the application.

Check the server logs after attempting to run the monitor.

See the error: Cannot read properties of undefined (reading 'lighthouseResult')

Expected behavior
The server should call the Google PageSpeed API and correctly process the lighthouseResult from the response, showing the monitor result.

Logs showing the error: Cannot read properties of undefined (reading 'lighthouseResult')

Additional context
The API key works when tested manually inside the container using the wget command, but fails when used by the application, indicating a potential issue with how the application handles the response.

**Comment by empiricompany** [comment]
I can confirm the same error occurs here too:

`2025-05-06T11:29:44.953015474Z 2025-05-06T11:29:44.952Z error: [StatusService](insertCheck) Cannot read properties of undefined (reading 'lighthouseResult') (details: Error inserting check for monitor: 6819ed2695ec18c1a903f20a)`

**Comment by ajhollid** [comment]
@draatman @empiricompany this issue should be resolved in the latest release, please reopen if you have any further issues with it.  Thank you!

**Comment by empiricompany** [comment]
@ajhollid thanks, but i have updated docker image to latest version on coolify
![coolify](https://github.com/user-attachments/assets/4e6085e9-01f5-401c-a47f-d941f0df291a)
I set the API key in the environment variables, but it still doesn't work, and I don't see the new setting to configure the API key from the interface.
The error is still the same.

```
2025-05-15T21:18:34.766325810Z 2025-05-15T21:18:34.765Z error: [StatusService](insertCheck) Cannot read properties of undefined (reading 'lighthouseResult') (details: Error inserting check for monitor: 6819ed2695ec18c1a903f20a)
2025-05-15T21:21:34.279315720Z 2025-05-15T21:21:34.277Z error: [StatusService](insertCheck) Cannot read properties of undefined (reading 'lighthouseResult') (details: Error inserting check for monitor: 6819ed2695ec18c1a903f20a)
```

**Comment by empiricompany** [comment]
this is my docker-compose
```yml
services:
  client:
    image: 'bluewaveuptime/uptime_client:latest'
    environment:
      - SERVICE_FQDN_CHECKMATE_80
      - 'UPTIME_APP_API_BASE_URL=${SERVICE_FQDN_CHECKMATESERVER_5000}/api/v1'
    depends_on:
      - server
  server:
    image: 'bluewaveuptime/uptime_server:latest'
    environment:
      - SERVICE_FQDN_CHECKMATESERVER_5000
      - 'JWT_SECRET=${SERVICE_PASSWORD_64_JWT}'
      - 'REFRESH_TOKEN_SECRET=${SERVICE_PASSWORD_64_REFRESH}'
      - 'SYSTEM_EMAIL_ADDRESS=${SYSTEM_EMAIL_ADDRESS:-test@example.com}'
      - 'SYSTEM_EMAIL_PASSWORD=${SERVICE_PASSWORD_64_EMAIL}'
      - 'SYSTEM_EMAIL_HOST=${SYSTEM_EMAIL_HOST}'
      - 'SYSTEM_EMAIL_PORT=${SYSTEM_EMAIL_PORT}'
      - 'PAGESPEED_API_KEY=${PAGESPEED_API_KEY}'
      - 'DB_CONNECTION_STRING=${DB_CONNECTION_STRING:-mongodb://mongodb:27017/uptime_db}'
      - 'REDIS_HOST=${REDIS_HOST:-redis}'
      - 'REDIS_PORT=${REDIS_PORT:-6379}'
      - 'DB_TYPE=${DB_TYPE:-MongoDB}'
      - 'TOKEN_TTL=${TOKEN_TTL:-99d}'
      - 'REFRESH_TOKEN_TTL=${REFRESH_TOKEN_TTL:-99d}'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    depends_on:
      - redis
      - mongodb
  redis:
    image: 'bluewaveuptime/uptime_redis:latest'
    volumes:
      - 'redis:/data'
  mongodb:
    image: 'bluewaveuptime/uptime_database_mongo:latest'
    volumes:
      - 'mongodb:/data/db'
    command:
      - mongod
      - '--quiet'

```

**Comment by ajhollid** [comment]
Hi @empiricompany ,

The PageSpeed API key is now set in the settings page, it is no longer set by environmental variable.

**Comment by empiricompany** [comment]
yes I saw in the release notes but I don't see the configuration with the docker images I posted, maybe you need to load the new builds? even if I see the version number 2.1 correctly in settings 🤔

**Comment by ajhollid** [comment]
> yes I saw in the release notes but I don't see the configuration with the docker images I posted, maybe you need to load the new builds? even if I see the version number 2.1 correctly in settings 🤔

Could be a coolify issue, I'm not familiar with it.  

Let's ping my colleague @vishnusn77, any thoughts here?

**Comment by vishnusn77** [comment]
Hi @empiricompany, I just deployed with coolify and I am able to add the pagespeed key in settings. 

![Image](https://github.com/user-attachments/assets/8f3c669c-feb8-48ab-a5b2-028f83f1aa5d)

Please make sure you are using the updated docker compose.yaml from our repo

**Comment by empiricompany** [comment]
Hi @vishnusn77 
I managed to successfully deploy the latest builds by modifying the docker-compose.yml, but the one used from the Coolify marketplace is the docker-compose.yml I posted, which contains outdated images.

![coolify](https://github.com/user-attachments/assets/25a86f0b-ab33-4d7d-862e-52dd06189f5c)

**Comment by chinedukoggu** [comment]
> Hi [@empiricompany](https://github.com/empiricompany), I just deployed with coolify and I am able to add the pagespeed key in settings.
> 
> ![Image](https://github.com/user-attachments/assets/8f3c669c-feb8-48ab-a5b2-028f83f1aa5d)
> 
> Please make sure you are using the updated docker compose.yaml from our repo

Can you include the link to the repo?
I have tried everything suggested here and even updated the coolify various times but the Pagespeed setting is still not visible and neither does it function as indicated by @empiricompany

**Comment by gorkem-bwl** [comment]
> > Hi [@empiricompany](https://github.com/empiricompany), I just deployed with coolify and I am able to add the pagespeed key in settings.
> > ![Image](https://github.com/user-attachments/assets/8f3c669c-feb8-48ab-a5b2-028f83f1aa5d)
> > Please make sure you are using the updated docker compose.yaml from our repo
> 
> Can you include the link to the repo? I have tried everything suggested here and even updated the coolify various times but the Pagespeed setting is still not visible and neither does it function as indicated by [@empiricompany](https://github.com/empiricompany)

Do you think this helps? Not a Docker expert but here it is: https://github.com/coollabsio/coolify/issues/6236#issuecomment-3253232716

**Comment by empiricompany** [comment]
@Gorkem-BWL, thanks, as I said before, it works with ghcr.io/bluewave-labs/checkmate:frontend-dist and other images.
but is not the latest version

<img width="988" height="134" alt="Image" src="https://github.com/user-attachments/assets/054f91b7-9ebf-43a9-afff-c698d0d74556" />

**Comment by empiricompany** [comment]
i think you must to pulish latest version 

<img width="613" height="667" alt="Image" src="https://github.com/user-attachments/assets/aa4cab8f-57c2-4b50-994a-754474a143af" />
