### ISSUE TITLE
Add Vietnamese and Japanese to the list of languages

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/Checkmate#2636]
The final language list should be: 

Chinese, English, German, Japanese, Turkish, Vietnamese, Ukrainian, Portuguese, Russian

**Comment by Charul192** [comment]
Hi! 👋
I'd like to work on this issue.
If it's not already assigned, could you please assign it to me?

Also, could you please point me to the file where the language list is defined?

**Comment by gorkem-bwl** [comment]
Hi @Charul192, thanks for your interest and willingness to contribute.

This issue does require a bit of familiarity with the codebase, so it's important to be comfortable navigating and understanding where to look for things like the language list. If you're still getting used to that, it might be helpful to start with smaller or more beginner-friendly projects first to build up confidence.

**Comment by Mohansai-M** [comment]
Hey @gorkem-bwl , I noticed the language list update task. If it's not already assigned, could you please assign it to me?

Also, just a heads-up — I’ve already worked on similar UI components recently and can deliver this one cleanly. Let me know — happy to take it up!

**Comment by gorkem-bwl** [comment]
Thanks @Mohansai-M - assigned.

**Comment by Mohansai-M** [comment]
Hi @gorkem-bwl , just confirming before I proceed —
I've started working on aligning the language list exactly with the final set you shared.
One quick check: applying this update will result in removing a few of the currently present languages.
Just wanted to make sure that’s intentional before I finalize it — don’t want to affect any existing translations unexpectedly.

**Comment by gorkem-bwl** [comment]
> Hi @gorkem-bwl , just confirming before I proceed —
> I've started working on aligning the language list exactly with the final set you shared.
> One quick check: applying this update will result in removing a few of the currently present languages.
> Just wanted to make sure that’s intentional before I finalize it — don’t want to affect any existing translations unexpectedly.

Thanks for confirming this. Yes, it's intentional :) I only wrote down the language names with more than 60% translation rate.

**Comment by Mohansai-M** [comment]
Hi @gorkem-bwl 
I've opened the PR with the finalized language list and related updates: [PR Link](https://github.com/bluewave-labs/Checkmate/pull/2639).
When you get a moment, could you please review it and let me know if any changes are needed? I’ll be happy to make the necessary updates.

Thanks in advance!

**Comment by gorkem-bwl** [comment]
Can you make sure you don't remove the PR checklist and then send out the PR again?

**Comment by Mohansai-M** [comment]
Thanks for letting me know! I’ve updated the PR with the complete checklist. Please let me know if there’s anything else I should improve.

**Comment by gorkem-bwl** [comment]
> Thanks for letting me know! I’ve updated the PR with the complete checklist. Please let me know if there’s anything else I should improve.

I still don't see the checklist? Since you have removed the template I am not sure everything is completed. For example you need to add a screenshot and it's not there?

**Comment by Mohansai-M** [comment]
I've now updated the PR description with the complete checklist and ensured all items are properly checked off.
Also, I’ve added a screenshot to the PR as requested to reflect the visible changes.
PR: https://github.com/bluewave-labs/Checkmate/pull/2646

**Comment by Mohansai-M** [comment]
Thank you @gorkem-bwl for trusting me with the task — glad to see the code has been merged!

**Comment by gorkem-bwl** [comment]
Thank you @Mohansai-M - next time if you can write this in your PR in 1 single line, this issue will be closed automatically: 

`Fixes #2636`
